### ISSUE TITLE
Topic button position is wrong

### ISSUE THREAD

**Issue by Laz0rSquid** [Laz0rSquid/ReactSettingsPagePrototype#4]
The expansion button for the topics needs to stay aligned to the top left corner of the parent div, currently it changes position once the content has been expanded

**Comment by donni106** [comment]
Maybe Flexbox could be a solution: https://css-tricks.com/snippets/css/a-guide-to-flexbox

**Comment by Laz0rSquid** [comment]
Fixed with latest commit
